/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface IncomeEntry {
  'icpTokenValue' : number,
  'date' : Time,
  'personId' : bigint,
  'timestamp' : Time,
  'incomeValue' : number,
  'icpAmount' : number,
}
export interface Person { 'id' : bigint, 'name' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<
    [bigint, number, number, Time, string, string],
    undefined
  >,
  'createPerson' : ActorMethod<[string, string, string], bigint>,
  'deleteEntry' : ActorMethod<[Time, string, string], undefined>,
  'deletePerson' : ActorMethod<[bigint, string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntries' : ActorMethod<[], Array<IncomeEntry>>,
  'getEntriesByPerson' : ActorMethod<[bigint], Array<IncomeEntry>>,
  'getPerson' : ActorMethod<[bigint], [] | [Person]>,
  'getPersons' : ActorMethod<[], Array<Person>>,
  'getRolling30DayIncomeSum' : ActorMethod<[bigint], number>,
  'getTotalIncome' : ActorMethod<[], number>,
  'getTotalIncomeByPerson' : ActorMethod<[bigint], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [UserProfile, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];